version: "3"
services:
  cron:
    image: commojun/cron:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      CRONTAB_FILE: /crontab
    restart: always
    volumes:
      - ./crontab:/crontab
    logging:
      options:
        max-size: "10m"
        max-file: "3"
